# Generated by Django 2.0.4 on 2018-05-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=12)),
                ('picture', models.ImageField(upload_to='picture/')),
                ('registered_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
