# Generated by Django 2.0.4 on 2018-05-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DPI', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('coord', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('alerts', models.CharField(max_length=50)),
            ],
        ),
    ]
