# Generated by Django 2.0.5 on 2018-05-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180504_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dpi', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('coordenadas', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=250)),
                ('emergencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='alert',
        ),
    ]
